apiVersion: v1
kind: Pod
metadata:
  name: php-spitback
  labels:
    app: php-spitback
spec:
  containers:
    - name: php-spitback
      image: ghcr.io/fredx30/php-spitback:master
      ports:
        - containerPort: 80
